### ISSUE TITLE
Support paging on Exchange API endpoints

### ISSUE THREAD

**Issue by mkropat** [rackerlabs/Invoke-RsCloudOfficeRequest#4]
The Exchange API endpoints[supports a different paging model](http://api-wiki.apps.rackspace.com/api-wiki/index.php/Exchange_Distribution_List_(Rest_API)) than most of the other endpoints in the Rackspace Cloud Office API. It would be nice if there was support built-in to `Invoke-RsCloudOfficeRequest` that supported unpaginating listings from the Exchange API endpoints.

**Comment by matthooper** [comment]
Do you have a preference for how this could be implemented?  Here are some ideas:

Idea 1: Check the API responses for an “Offset” property, and if it’s not present, attempt to page using the Marker approach.

Idea 2: Recognize which URLs use marker paging. A list of URL patterns would have to be kept up to date.

Idea 3: Specify the paging model as a script parameter. Seems very prone to error.


I lean towards #1 since its probably easy to implement than #2 but I don’t like that it looks for the absence of the offset/size paging approach which breaks down if a 3rd paging model is added later. I really don’t like #3.

**Comment by mkropat** [comment]
I hadn't really thought it through, but I really like your Idea #1.

It looks like the API always returns either `offset` or `marker` (depending on the route), so that looks like a reliable way that `Invoke-RsCloudOffice` could distinguish between the two cases so that users would never have to think about it. It's possible that the property names would be different for future routes, but there's generally only two types of paging (offset vs marker/keyset), so I'm not too worried about that changing.

It should be easy to implement too, although I can't start on it at the moment.

**Comment by mkropat** [comment]
@matthooper: I added a pull request (#5) that implements paging for the Exchange endpoints based on your idea 1.

Feel free to test it and let me know if it works for you, if you want to. I want to do some more testing later, then if it looks good I'll merge it and put together a new release.

**Comment by matthooper** [comment]
Awesome! Ill test but I'm traveling this week so may not be able to get to it until next week.





-------- Original message --------

**Comment by mkropat** [comment]
Implemented by #5.
